Change to Team OctOS release tools

diff --git a/tools/squisher b/tools/squisher
--- a/tools/squisher
+++ b/tools/squisher
@@ -1,109 +1,175 @@
-#!/bin/sh
+#!/bin/bash
 #
-# Squish a Vanir otapackage for distribution
-# credit for original version: CM
+# Squish a CM otapackage for distribution
+# cyanogen
 #
-
-export ANDROID_BUILD_TOP=$ANDROID_BUILD_TOP
-
 . $ANDROID_BUILD_TOP/vendor/to/tools/functions
 
+OUT_TARGET_HOST=`uname -a | grep Darwin`
+if [ -z "$OUT_TARGET_HOST" ]
+then
+   OUT_TARGET_HOST=linux-x86
+   MD5=md5sum
+   XARGS="xargs --max-args=1 --max-procs `grep 'processor' /proc/cpuinfo|wc -l`"
+   SED=sed
+else
+   OUT_TARGET_HOST=darwin-x86
+   MD5=md5
+   XARGS="xargs -n 1 -P `sysctl hw.ncpu | awk '{print $2}'`"
+   SED=gsed
+fi
+
 if [ -z "$OUT" -o ! -d "$OUT" ]; then
-    echo -e $CL_RED"ERROR: $0 only works with a full build environment. $OUT should exist."$CL_RST
-    exit 1
+	echo -e $CL_RED"ERROR: $0 only works with a full build environment. $OUT should exist."$CL_RST
+	exit 1
 fi
 
-OTAPACKAGE=$OTA_PACKAGE_PATH
-
-if [ ! -f "$OTAPACKAGE" ]; then
-    echo -e $CL_RED"$OTAPACKAGE doesn't exist!"$CL_RST;
-    exit 1
-fi
-
+OPTICHARGER=$ANDROID_BUILD_TOP/vendor/to/tools/opticharger
 QUIET=-q
+DELETE_BINS="applypatch applypatch_static check_prereq recovery updater"
+DELETE_LIBS="libc_malloc_debug_leak.so libc_malloc_debug_qemu.so"
+DELETE_FONTS="MTLmr3m.ttf"
+DELETE_MEDIA="*.qmg"
 
 REPACK=$OUT/repack.d
-printf "Sanitizing environment..."
+echo -e "Sanitizing Environment..."
 rm -rf $REPACK
 mkdir -p $REPACK
-echo
+echo -e
 
 # Unpack the otapackage and opticharge all apks
 mkdir $REPACK/ota
 (
 cd $REPACK/ota
-printf "Unpacking $OTAPACKAGE..."
+echo -e "Unpacking $OTAPACKAGE..."
 unzip $QUIET $OTAPACKAGE
-ln -s  $OUT/data $REPACK/ota/data
-echo
+echo -e
 
 # Move all apks to the same directory so xargs can
 # use also with framework-res.apk. This allow process
 # framework-res.apk in parallel with other apks
 mkdir -p $REPACK/parallel
 cd $REPACK/parallel
-find $REPACK/ota/system -name '*.apk' | while read APK; do
-    ln -s $APK .
-done
+cp $REPACK/ota/system/framework/framework-res.apk .
+cp $REPACK/ota/system/app/*.apk .
 
-find ./ -name \*.apk | $HALFXARGS schedtool -B -n 1 -e ionice -n 1 $OPTICHARGER
+# Do optimization in parallel
+find ./ -name \*.apk | $XARGS $OPTICHARGER
+
+# Move optimized apks to repack directory
+mv -f $REPACK/parallel/framework-res.apk $REPACK/ota/system/framework/framework-res.apk
+mv -f $REPACK/parallel/*.apk $REPACK/ota/system/app/
+
+# Optimize /priv-app/
+cp $REPACK/ota/system/priv-app/*.apk .
+find ./ -name \*.apk | $XARGS $OPTICHARGER
+mv -f $REPACK/parallel/*.apk $REPACK/ota/system/priv-app/
 
 # Return to directory
 cd $REPACK/ota
 rm -rf $REPACK/parallel
 )
 
-# move utilities
-[ -e $OUT/utilities ] && cp $OUT/utilities/* $REPACK/ota/system/xbin/
+# Fix build.prop
+$SED -i \
+	-e '/ro\.kernel\.android\.checkjni/d' \
+	-e '/ro\.build\.type/s/eng/user/' \
+	$REPACK/ota/system/build.prop
 
 # Determine what to name the new signed package
-MODVERSION=`sed -n -e'/ro\.modversion/s/^.*=//p' $OUT/system/build.prop`
-OUTVERSION="$TARGET_PRODUCT"_"$MODVERSION"
-OUTFILE=$OUT/$OUTVERSION.zip
+MODVERSION=`sed -n -e'/ro\.to\.version/s/^.*=//p' $OUT/system/build.prop`
+# Check for '_' in product name
+if [ "`echo -e $TARGET_PRODUCT | cut -d '_' -f3`" != "" ]
+then
+TARGET_PRODUCT_FINAL=`echo -e $TARGET_PRODUCT | cut -d '_' -f2,3`
+else
+TARGET_PRODUCT_FINAL=`echo -e $TARGET_PRODUCT | cut -d '_' -f2`
+fi
+echo -e $CL_CYN"MODVERSION: $MODVERSION"$CL_RST
+OUTFILE=$OUT/$MODVERSION-$TARGET_PRODUCT_FINAL.zip
+
+# Delete unnecessary binaries
+( cd $REPACK/ota/system/bin; echo -e $DELETE_BINS | xargs rm -f; )
+
+# Delete unnecessary libraries
+( cd $REPACK/ota/system/lib; echo -e $DELETE_LIBS | xargs rm -f; )
+
+# Delete Offline charging mode files
+( cd $REPACK/ota/system/media; echo -e $DELETE_MEDIA | xargs rm -f; )
+
+if [ "$TARGET_PRODUCT_FINAL" != "infuse4g" ]
+then
+# No need for modem.bin
+rm -f $REPACK/ota/modem.bin
+fi
+
+# No need for media/video
+rm -rf $REPACK/ota/system/media/video
+
+# Delete Unnecessary Fonts
+( cd $REPACK/ota/system/fonts; echo -e $DELETE_FONTS | xargs rm -f; )
+
+# No need for tts
+rm -rf $REPACK/ota/system/tts
+
+# No need for srec
+rm -rf $REPACK/ota/system/usr/srec
+
+# No need for recovery
+rm -rf $REPACK/ota/recovery
+rm -rf $REPACK/ota/system/etc/recovery-resource.dat
+
+# Strip modules
+[ -d $REPACK/ota/system/lib/modules ] && \
+	find $REPACK/ota/system/lib/modules -name "*.ko" -print0 | xargs -0 arm-eabi-strip --strip-unneeded
+
+if [ "$TO_CHANGELOG" = true ]
+then
+# Add changelog
+. $ANDROID_BUILD_TOP/vendor/to/tools/changelog
+else
+echo -e "No changelog..."
+echo -e
+fi
 
 # Pack it up and sign
-printf "Zipping package..."
+echo -e "Zipping package..."
 ( cd $REPACK/ota; zip $QUIET -r $REPACK/update.zip . )
-echo
-printf "Signing package..."
+echo -e
+echo -e "Signing package..."
 SECURITYDIR=$ANDROID_BUILD_TOP/build/target/product/security
-java -Xmx2048m \
-    -jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar \
-    -w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
-    $REPACK/update.zip $OUTFILE
-echo
-printf "Cleaning up..."
+java -Xmx1024m \
+	-jar $OUT/../../../host/$OUT_TARGET_HOST/framework/signapk.jar \
+	-w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
+	$REPACK/update.zip $OUTFILE
+echo -e
+echo -e "Cleaning up..."
 rm -rf $REPACK
-echo
+echo -e
+
+echo -e $CL_CYN"▄▄▄█████▓▓█████ ▄▄▄       ███▄ ▄███▓    ▒█████   ▄████▄  ▄▄▄█████▓ ▒█████    ██████"$CL_RST
+echo -e $CL_CYN"▓  ██▒ ▓▒▓█   ▀▒████▄    ▓██▒▀█▀ ██▒   ▒██▒  ██▒▒██▀ ▀█  ▓  ██▒ ▓▒▒██▒  ██▒▒██    ▒"$CL_RST
+echo -e $CL_CYN"▒ ▓██░ ▒░▒███  ▒██  ▀█▄  ▓██    ▓██░   ▒██░  ██▒▒▓█    ▄ ▒ ▓██░ ▒░▒██░  ██▒░ ▓██▄ "$CL_RST  
+echo -e $CL_CYN"░ ▓██▓ ░ ▒▓█  ▄░██▄▄▄▄██ ▒██    ▒██    ▒██   ██░▒▓▓▄ ▄██▒░ ▓██▓ ░ ▒██   ██░  ▒   ██▒"$CL_RST
+echo -e $CL_CYN"  ▒██▒ ░ ░▒████▒▓█   ▓██▒▒██▒   ░██▒   ░ ████▓▒░▒ ▓███▀ ░  ▒██▒ ░ ░ ████▓▒░▒██████▒▒"$CL_RST
+echo -e $CL_CYN"  ▒ ░░   ░░ ▒░ ░▒▒   ▓▒█░░ ▒░   ░  ░   ░ ▒░▒░▒░ ░ ░▒ ▒  ░  ▒ ░░   ░ ▒░▒░▒░ ▒ ▒▓▒ ▒ ░"$CL_RST
+echo -e $CL_CYN"    ░     ░ ░  ░ ▒   ▒▒ ░░  ░      ░     ░ ▒ ▒░   ░  ▒       ░      ░ ▒ ▒░ ░ ░▒  ░ ░"$CL_RST
+echo -e $CL_CYN"  ░         ░    ░   ▒   ░      ░      ░ ░ ░ ▒  ░          ░      ░ ░ ░ ▒  ░  ░  ░"$CL_RST  
+echo -e $CL_CYN"            ░  ░     ░  ░       ░          ░ ░  ░ ░                   ░ ░        ░"$CL_RST  
+echo -e $CL_CYN"                                                ░"$CL_RST
 
 # Create a md5 checksum image of the repacked package
 (
-echo -e ""
-echo -e ""
-echo -e $CL_GRN"================  "$CL_RST OTA package information $CL_GRN"  ================"$CL_RST
-echo -e ""
-echo -e $CL_BLU"Product name:"$CL_RST $OTAPACKAGE
-
 img=`basename $OUTFILE`
 cd `dirname $OUTFILE`
-STRING=$OTA_PACKAGE_PATH
-OTASIZE=`ls -lah $STRING | awk '{ print $5}' `
-echo -e $CL_BLU"Package Size: "$CL_YLW "$OTASIZE" $CL_RST
-echo -e $CL_BLU"Target Location: " $CL_RST
-echo -e $CL_YLW"$OTA_PACKAGE_PATH" $CL_RST
-echo ""
-
-$MD5 $img >$img.md5
-ZIPSIZE=`ls -lah $OUTFILE | awk '{ print $5}' `
-echo -e $CL_GRN"================"$CL_RST $TARGET_PRODUCT-$TARGET_BUILD_VARIANT: $CL_RED"completed"$CL_RST $CL_GRN"================"$CL_RST
-echo ""
-echo -e $CL_BLU"Product name:"$CL_RST $OUTVERSION.zip
-echo -e $CL_BLU"Package Size: "$CL_YLW"$ZIPSIZE     "
-echo -e $CL_BLU"md5:"$CL_RST $CL_YLW" $(cat $img.md5 | awk '{ print $1 }')"$CL_RST
-echo -e $CL_BLU"Target location:"$CL_RST
-echo -e $CL_YLW $OUTFILE $CL_RST
-echo ""
-echo ""
+$MD5 $img >$img.md5sum
+echo -e
+echo -e $CL_CYN"===========-Package complete-==========="$CL_RST
+echo -e $CL_CYN"zip:"$CL_MAG" $OUTFILE"$CL_RST
+echo -e $CL_CYN"md5:"$CL_MAG" $(cat $img.md5sum | awk '{ print $1 }')"$CL_RST
+echo -e $CL_CYN"size:"$CL_MAG" $(ls -lah $OUTFILE | awk '{ print $5}') ($(ls -la $OUTFILE | awk '{ print $5}'))"$CL_RST
+echo -e $CL_CYN"========================================"$CL_RST
+echo -e
 )
 
 exit 0
